version: "3.8"

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: bitwarden
    restart: always
    ports:
      - "${BITWARDEN_PORT}:80"   # HTTP
      - "443:443" # HTTPS
    env_file:
      - .env
    environment:
      - WEBSOCKET_ENABLED=true
        #- ROCKET_TLS={certs="ssl/bitwarden.crt",key="ssl/bitwarden.key"} 
        #- ROCKET_CERT=/ssl/bitwarden.crt
        #- ROCKET_KEY=/ssl/bitwarden.key
      - SIGNUPS_ALLOWED=false
      - SHOW_PASSWORD_HINT=false
      - ROCKET_WORKERS=10
      - BITWARDEN_PORT=${BITWARDEN_PORT}
    volumes:
      - /home/${USER}/Documents/containers/bitwarden/data:/data
      - /home/${USER}/Documents/containers/bitwarden/config:/config
      - /home/${USER}/Documents/containers/bitwarden/ssl:/ssl
