version: "3.8"
services:
  heimdall:
    image: linuxserver/heimdall:latest
    container_name: heimdall
    ports:
      - "${HEIMDALL_PORT}:80"
      #- 443:443
    env_file:
      - ../docker/common.env
    volumes:
      - /home/${USER}/Documents/containers/heimdall/config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    restart: unless-stopped
