version: '2'

services:
  db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - /home/${USER}/Documents/containers/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=server
      - MYSQL_PASSWORD=server
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    restart: always
    env_file:
      - ../docker/common.env
    ports:
      - "${NEXTCLOUD_PORT}:80"
    links:
      - db
    volumes:
      - /home/${USER}/Documents/containers/nextcloud/nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=server
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
