version: '3.8'
services:
  jenkins:
    build:
      context: ./docker  # Specify the path to the folder containing your Dockerfile
      dockerfile: Dockerfile  # Name of your Dockerfile (assuming it's named Dockerfile)
    privileged: true
    env_file:
      - ../docker/common.env
    user: root
    ports:
    - "${JENKINS_PORT_1}:8080"
    - "${JENKINS_PORT_2}:50000"
    container_name: jenkins
    volumes:
      - /home/${USER}/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
