version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    #network_mode: 'host'
    volumes:
      - /home/our-server/Documents/containers/jellyfin/config:/config
      - /home/our-server/Documents/containers/jellyfin/cache:/cache
      - /home/our-server/Documents/containers/jellyfin/media:/media
      - /home/our-server/Documents/containers/jellyfin/media2:/media2:ro
    ports:
      - "8096:8096"
      - "8920:8920"
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=http://192.168.1.251
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    #extra_hosts:
    #  - "host.docker.internal:host-gateway"
