version: '3'

services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    env_file:
      - ../docker/common.env
    ports:
      - "${PORTAINER_PORT}:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/${USER}/Documents/containers/portainer/portainer_data:/data

volumes:
  portainer_data:

