version: '3.9'
services:
  db:
    image: postgres:14
    restart: always
    env_file:
      - ../docker/common.env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: Default

volumes:
  db_data:
