version: '3.9'
services:
  db:
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: server
      POSTGRES_PASSWORD: server
      POSTGRES_DB: Default

volumes:
  db_data:
